config/routes.rb
Ganttproject::Engine.routes.draw do

  resources :projects do
    resources :resources
    resources :tasks
    resources :links
  end
  root :to => 'projects#index'

  match "ganttproject/projects/datagrid", :to => "projects#datagrid", :as => "data_grid", :via => "get"
  match "ganttproject/projects/datagrid_action", :to => "projects#datagrid_action", :as => "datagrid_action", :via => "get"
  match "ganttproject/projects/:id/datagantt", :to => "projects#datagantt", :as => "data_gantt", :via => "get"
  match "ganttproject/projects/:id/datagantt_action", :to => "projects#datagantt_action", :as => "datagantt_action", :via => "post"

end

app/models/ganttproject/assignment.rb
module Ganttproject
  class Assignment < ActiveRecord::Base
    belongs_to :tasks
    belongs_to :resources
  end
end

app/models/ganttproject/historical.rb
module Ganttproject
  class Historical < ActiveRecord::Base
  end
end

app/models/ganttproject/link.rb
module Ganttproject
  class Link < ActiveRecord::Base
    belongs_to :project

    validates_presence_of :project_id
    validates_presence_of :target
    validates_presence_of :source

    def from_params(params, session, id)
      self.source = params["#{id}_source"].to_i
      self.target = params["#{id}_target"].to_i
      self.gtype = params["#{id}_type"].to_i
      self.project_id=params[:id]
    end

    def json_data
      Rails.cache.fetch("#{self.cache_key}/json_data", expires_in: 30.days) do
        {
          :id => self.id,
          :source => self.source,
          :target => self.target,
          :type =>  self.gtype
        }
      end

    end

  end
end

app/models/ganttproject/resource.rb
module Ganttproject
  class Resource < ActiveRecord::Base
    has_many :assignments, dependent: :destroy
    has_many :tasks, through: :assignments
    belongs_to :project
  end
end

app/controllers/ganttproject/application_controller.rb
module Ganttproject
  class ApplicationController < ActionController::Base
    protect_from_forgery except: :index
    before_filter :verify_session
    include Rails.application.helpers

    def verify_session
    	render nothing: true, status: :unauthorized if current_user.nil?
    end
  end
end

app/controllers/ganttproject/assignments_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class AssignmentsController < ApplicationController
    before_action :set_assignment, only: [:show, :edit, :update, :destroy]

    # GET /assignments
    def index
      @assignments = Assignment.all
    end

    # GET /assignments/1
    def show
    end

    # GET /assignments/new
    def new
      @assignment = Assignment.new
    end

    # GET /assignments/1/edit
    def edit
    end

    # POST /assignments
    def create
      @assignment = Assignment.new(assignment_params)

      if @assignment.save
        redirect_to @assignment, notice: 'Assignment was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /assignments/1
    def update
      if @assignment.update(assignment_params)
        redirect_to @assignment, notice: 'Assignment was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /assignments/1
    def destroy
      @assignment.destroy
      redirect_to assignments_url, notice: 'Assignment was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_assignment
        @assignment = Assignment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def assignment_params
        params.require(:assignment).permit(:task_id, :resource_id, :start, :finish)
      end
  end
end

app/controllers/ganttproject/ganttproject_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class GanttprojectController < ApplicationController

    def index
      render :text => 'Hello world'
    end

  end
end

app/controllers/ganttproject/links_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class LinksController < ApplicationController
    before_action :set_link, only: [:show, :edit, :update, :destroy]
    before_action :get_project

    def get_project
      @project = Project.find(params[:project_id])
    end

    # GET /links
    # GET /links.json
    def index
      @links = @project.links.all
    end

    # GET /links/1
    # GET /links/1.json
    def show
      @link = @project.links.find(params[:id])
    end

    # GET /links/new
    def new
      @link = @project.links.new()
    end

    # GET /links/1/edit
    def edit
    end

    # POST /links
    def create
      @link = Link.new(link_params)

      if @link.save
        redirect_to @link, notice: 'Link was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /links/1
    def update
      if @link.update(link_params)
        redirect_to @link, notice: 'Link was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /links/1
    def destroy
      @link.destroy
      redirect_to links_url, notice: 'Link was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_link
        @link = Link.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def link_params
        params.require(:link).permit(:source, :target, :gtype, :project_id)
      end
  end
end

app/controllers/ganttproject/projects_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    skip_before_filter :verify_authenticity_token

    # GET /projects
    def index
      #@projects = Ganttproject::Project.all
    end

    # GET /projects/1
    def show
    end

    # GET /projects/new
    def new
      @project = Ganttproject::Project.new
    end

    # GET /projects/1/edit
    def edit
    end


    # POST /projects
    # POST /projects.json
    def create
      @project = Ganttproject::Project.new(project_params)
      @project.sector_id = params[:sector_id].to_i
      respond_to do |format|
        if @project.save
          sector = ::Sector.find(params[:sector_id])
          sector.master_project_id = @project.id
          sector.save
          @project.process_project_file
          format.html { redirect_to @project, notice: 'Proyecto fue creado satifactoriamente.' }
          format.json { render nothing: true }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /projects/1
    # PATCH/PUT /projects/1.json
    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'Proyecto fue actualizado satifactoriamente.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /projects/1
    # DELETE /projects/1.json
    def destroy
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Proyecto fue eliminado satifactoriamente.' }
        format.json { head :no_content }
      end
    end



    def datagantt
      @project = Project.find(params[:id])
      @tasks = @project.tasks.order(id: :asc)
      @links = @project.links
      render :json => {
                 :data =>
                     @tasks.map do |task|
                        task.json_data
                      end.compact,

                 :links =>
                     @links.map do |link|
                       link.json_data
                     end

             }, status: :ok

    end


    def datagantt_action


      params['ids'].split(',').each do |id|
        @id   = params["#{id}_id"].to_i
        @mode = params["#{@id}_!nativeeditor_status"]
        @gantt_mode = params['gantt_mode']

        case @gantt_mode
          when "tasks"
            case @mode
              when "inserted"
                task = Task.new
                task.from_params(params, @id)
                if task.save
                  @tid = task.id
                end

              when "deleted"
                task = Task.find(@id)
                task.destroy
                @tid= @id

              when "updated"
                task = Task.find(@id)
                task.from_params(params, @id)
                if task.save
                  @tid = @id
                end
            end
          when "links"
            case @mode
              when "inserted"
                link = Link.new
                link.from_params(params, session, @id)
                if link.save
                  @tid = link.id
                end

              when "deleted"
                link = Link.find(@id)
                link.destroy
                @tid = @id

              when "updated"
                link = Link.find(@id)
                link.from_params(params, session, @id)
                if link.save
                  @tid = @id
                end
            end
        end
      end

    end



    def datagrid
      @projects = Project.all

      render :json => {
                 :total_count => @projects.length,
                 :pos => 0,
                 :rows => @projects.map do |project|
                   {
                       :id => project.id,
                       :data => [project.name,
                                 project.file_name,
                                 project.resources.count,
                                 project.tasks.count,
                                 "<a href='/ganttproject/projects/"+project.id.to_s+"'>Ver</a>
                                 <a href='/ganttproject/projects/"+project.id.to_s+"/edit'>Editar</a>"
                                #"<form action='/ganttproject/projects/"+project.id.to_s+"' method='get' class='button_to'><input type='submit' value='Ver'></form>"
                       ]
                   }
                 end
             }
    end

    def datagrid_action
      @mode = params["!nativeeditor_status"]
      name = params["c0"]
      @id = params["gr_id"]

      case @mode
        when "inserted"
          project = Project.create :name => name
          if project.save
            @tid = project.id
          end
        when "deleted"
          Project.find(@id).destroy
          @tid = @id

        when "updated"
          project = Project.find(@id)
          project.name = name
          project.save
          @tid = @id
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Ganttproject::Project.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def project_params
        params.require(:project).permit(:name, :file)
      end
  end
end

app/controllers/ganttproject/resources_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class ResourcesController < ApplicationController
    before_action :set_resource, only: [:show, :edit, :update, :destroy]
    before_action :get_project

    def get_project
      @project = Project.find(params[:project_id])
    end
    # GET /resources
    # GET /resources.json
    def index
      @resources = @project.resources.all
    end

    # GET /resources/1
    # GET /resources/1.json
    def show
      @resources = @project.resources.find(params[:id])
    end

    # GET /resources/new
    def new
      @resource = @project.resources.new
    end

    # GET /resources/1/edit
    def edit
    end


    # POST /resources
    def create
      @resource = @project.resources.new(params[:resource])

      if @resource.save
        redirect_to @resource, notice: 'Recurso creado satifactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /resources/1
    def update
      if @resource.update(resource_params)
        redirect_to @resource, notice: 'Recurso actualizado satifactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /resources/1
    def destroy
      @resource.destroy
      redirect_to resources_url, notice: 'Recurso eliminado satifactoriamente.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_resource
        @resource = @project.resources.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def resource_params
        params.require(:resource).permit(:name, :initials, :max_units, :cost, :project_id)
      end
  end
end

app/controllers/ganttproject/tasks_controller.rb
require_dependency "ganttproject/application_controller"

module Ganttproject
  class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :get_project

    def get_project
      @project = Project.find(params[:project_id])
    end

    # GET /tasks
    # GET /tasks.json
    def index
      @tasks = @project.tasks.all
    end

    # GET /tasks/1
    # GET /tasks/1.json
    def show
      @task = @project.tasks.find(params[:id])
    end

    # GET /tasks/new
    def new
      @task = @project.tasks.new(:parent_id => params[:parent_id])
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks
    def create
      @task = Task.new(task_params)

      if @task.save
        redirect_to @task, notice: 'Task was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /tasks/1
    def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tasks/1
    def destroy
      @task.destroy
      redirect_to tasks_url, notice: 'Task was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_task
        @task = @project.tasks.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def task_params
        params.require(:task).permit(:name, :start, :finish, :duration, :progress, :parent_id, :project_id)
      end
  end
end

app/helpers/ganttproject/application_helper.rb
module Ganttproject
  module ApplicationHelper
  end
end

app/helpers/ganttproject/assignments_helper.rb
module Ganttproject
  module AssignmentsHelper
  end
end

app/helpers/ganttproject/ganttproject_helper.rb
module Ganttproject
  module GanttprojectHelper
  end
end

app/helpers/ganttproject/links_helper.rb
module Ganttproject
  module LinksHelper
  end
end

app/helpers/ganttproject/projects_helper.rb
module Ganttproject
  module ProjectsHelper
  end
end

app/helpers/ganttproject/resources_helper.rb
module Ganttproject
  module ResourcesHelper
  end
end

app/helpers/ganttproject/tasks_helper.rb
module Ganttproject
  module TasksHelper

    def nested_tasks(tasks)
      tasks.map do |task, sub_task|
        render(task) + content_tag(:div, nested_tasks(sub_task), :class => "nested_tasks")
      end.join.html_safe
    end

  end
end

app/views/ganttproject/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Archivo" %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ganttproject/projects/datagantt_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <action type="<%= @mode %>" sid="<%= @id %>" tid="<%= @tid %>" />
</data>

app/views/ganttproject/projects/datagrid_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <action type="<%= @mode %>" sid="<%= @id %>" tid="<%= @tid %>" />
</data>

app/views/ganttproject/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/ganttproject/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyectos</h1>

<br>
<div id="grid_projects" style="width: 100%; height: 400px;"></div>
<br>

<%= button_to "Importar Proyecto", new_project_path , method: :get %>
<!--<input type="button" value="Nuevo Projecto" onclick="grid.addRow(grid.uid(),['Nuevo Proyecto','',0,0])" />
<input type="button" value="Borrar"  onclick="if (confirm('Esta seguro que desea borrar este proyecto?')){grid.deleteSelectedRows();}" />-->

<br>
<br>
<br>

<script type="text/javascript" charset="UTF-8">
    var grid = new dhtmlXGridObject("grid_projects");
    grid.setImagePath("assets/imgs/");
    grid.setHeader("Nombre Proyecto, Nombre Archivo,N° Resources ,N° Task, Detalle ");
    grid.setColSorting("str,str,int,int,str");
    grid.setColTypes("ed,ro,ro,ro,ro");
    grid.setInitWidths("*,250,100,100,80");
    grid.setSkin("dhx_skyblue");
    grid.init();
    grid.load("<%= data_grid_path %>", "json");
    var dp_grid = new dataProcessor("<%= datagrid_action_path %>");
    dp_grid.init(grid);
</script>

app/views/ganttproject/projects/new.html.erb
<h1>Nuevo Proyecto</h1>

<%= form_for(@project) do |f| %>
    <div class="field">
      <%= f.label "Nombre"%><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="field">
      <%= f.label "Archivo" %><br>
      <%= f.file_field :file %>
    </div>
    <br>
    <br>
    <div class="actions">
      <%= f.submit "Cargar" %>
    </div>
<% end %>
<br>

<%= link_to 'Volver', projects_path %>

app/views/ganttproject/projects/show.html.erb
<div id="gantt_projects"  class="jumbotron"></div>


<style>
    .gantt_cell,
    .gantt_task_content,
    .gantt_grid_scale,
    .gantt_task_scale
    {
        font-size: 10px;
    }

    #title{
        height: 120px;

    }

    #gantt_projects{
        height: auto;
        width: 100%;
        position: absolute;
        top: 120px;
        bottom: 0;
    }


</style>

<script type="text/javascript">
    gantt.init("gantt_projects");
    gantt.config.xml_date = "%d-%m-%Y";
    gantt.config.columns = [
        {name:"text",       label:"Tarea",  width:"200", tree:true },
        {name:"start_date", label:"Fecha Inicio", width:"80", align: "center" },
        {name:"end_date",   label:"Fecha Final", width:"80", align: "center" },
        {name:"duration",   label:"Duracion",   width:"85", align: "center" , template:function(obj){return obj.duration+" dias"}},
        {name:"add",        label:"",           width:44 }
    ];
    gantt.config.scale_unit= "week";
    //gantt.config.autosize = "y";

    gantt.clearAll();
    gantt.load("<%= data_gantt_path %>", "json");
    dp_gantt = new dataProcessor("<%= datagantt_action_path %>");
    dp_gantt.init(gantt);
</script>